name: Build HTML5 and upload to itch.io

on:
  push:
    branches: [build]
  workflow_dispatch:

jobs:
  build:
    name: Build and upload the HTML5 version
    runs-on: ubuntu-latest
    steps:
      - name: Install dependencies
        run: |
          sudo apt update
          sudo apt install python3 cmake emscripten nodejs htmlmin ninja-build
      - name: Checkout
        uses: actions/checkout@v4
      - name: Build
        run: |
          emcmake cmake -DPLATFORM=Web -DCMAKE_BUILD_TYPE=Release -B build-html5 -S ${{github.workspace}} -G Ninja
          cmake --build build-html5 -j 4
      - name: Assemble dist-files
        run: |
          mkdir -p dist-html5
          cd build-html5
          cp index.html CodenamePedestrian.data CodenamePedestrian.wasm CodenamePedestrian.js ../dist-html5
      - name: Upload to itch.io
        uses: manleydev/butler-publish-itchio-action@master
        env:
          BUTLER_CREDENTIALS: ${{ secrets.BUTLER_CREDENTIALS }}
          CHANNEL: html5
          ITCH_GAME: codename-pedestrian
          ITCH_USER: nonk123
          PACKAGE: dist-html5
